/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
const fileMap = {
  
  "ocr.baml": "generator typescript {\n  output_type \"typescript\"\n  output_dir \"../\"\n  version \"0.89.0\"\n}\n\nclass Quote {\n  quote string\n  author string\n}\n\nclient<llm> Gemini {\n  provider google-ai\n  options {\n    model \"gemini-2.0-flash\"\n    api_key env.GEMINI_API_KEY\n  }\n}\n\nclient<llm> OpenRouter {\n  provider openai-generic\n  options {\n    base_url \"https://openrouter.ai/api/v1\"\n    model \"qwen/qwen2.5-vl-3b-instruct:free\"\n    api_key env.OPENROUTER_API_KEY\n  }\n}\n\nfunction ExtractTextFromImage(imageData: image) -> Quote {\n  prompt #\"\n  Extract visible quote from attached image\n  {{imageData}}\n\n  Dont use quotes in your response\n  {{ ctx.output_format }}\n  \"#\n  client Gemini\n}\n\ntest TestExtractTextFromImage {\n  functions [ExtractTextFromImage]\n  args {\n    imageData {\n      file \"./sun-tzu.jpg\"\n    }\n  }\n}\n",
}
export const getBamlFiles = () => {
    return fileMap;
}